# Generated by Django 4.2 on 2023-04-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_remove_author_email_remove_author_headshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="books"),
        ),
    ]
